INSERT INTO [dbo].[students] (  
           [username]
           ,[password]
           ,[id_donvi]
           ,[avatar]
           ,[name]
           ,[phone]
           ,[id_permission]
           ,[id_class]
           ,[id_speciality]
           ,[is_testing]
           ,[time_start]
           ,[time_remaining]
           ,[last_login]
           ,[last_seen]
           ,[last_seen_url]
           ,[timestamps])
SELECT   [username]
           ,[password]
           ,[id_donvi]
           ,[avatar]
           ,[name]
           ,[phone]
           ,[id_permission]
           ,[id_class]
           ,[id_speciality]
           ,[is_testing]
           ,[time_start]
           ,[time_remaining]
           ,[last_login]
           ,[last_seen]
           ,[last_seen_url]
           ,[timestamps] FROM [dbo].[students$]

--xóa key
		     DBCC CHECKIDENT ([students], RESEED, 1)